### ISSUE TITLE
upperDir のバグ

### ISSUE THREAD

**Issue by whats-up** [mick-whats/rrq#1]
upperDirが絶対パスにしか対応していない。相対パスを引数に与えた時の対応。

**Comment by mick-whats** [comment]
> path.dirname(p)
> パスに含まれるディレクトリ名を返します。Unixの dirname コマンドと同様です。

[path.dirname(p)](http://nodejs.jp/nodejs.org_ja/docs/v0.10/api/path.html)

上記のメソッドで統合
